- hosts: all
  become: true
  pre_tasks:

  - name: Install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Update repository index (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: elastic
  become: true
  roles:
    - elastic

- hosts: kibana
  become: true
  roles:
    - kibana

- hosts: logstash
  become: true
  roles:
    - logstash

- hosts: ubuntu_nagios
  become: true
  roles:
    - nagios

- hosts: influxdb
  become: true
  roles:
    - influxdb

- hosts: grafana
  become: true
  roles:
    - grafana

- hosts: prometheus
  become: true
  roles:
    - prometheus

- hosts: lamp_stack
  become: true
  roles:
    - lampstack
